version: 2.1
orbs:
  android: circleci/android@2.1.2
machine:
  environment:
    JAVA_HOME: /usr/lib/jvm/java-9-oracle
dependencies:
  pre:
    - sudo add-apt-repository -y ppa:webupd8team/java; sudo apt-get update
    - echo "oracle-java9-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
    - echo "oracle-java9-installer shared/accepted-oracle-license-v1-1 seen true" | sudo debconf-set-selections
    - sudo apt-get -y install oracle-java9-installer
    - sudo apt-get install oracle-java9-set-default
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:19.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@8.19"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - run:
          name: install ionic cli
          command: "sudo npm install -g @ionic/cli"
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: ionic build --prod
      - run:
          name: sync capacitor
          command: npx cap sync
      - run:
          name: install java
          command: |
                sudo apt-get update
                sudo apt install default-jre
                java -version
                sudo apt install default-jdk
      - run:
          name: install android sdk
          command: |
            sudo apt install android-sdk
            export ANDROID_HOME=/usr/lib/android-sdk
      - run:
          name: install android build tools
          command: |
            wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
            unzip commandlinetools-linux-6609375_latest.zip -d cmdline-tools
            sudo mkdir --parents "$ANDROID_HOME/cmdline-tools/latest"
            sudo mv cmdline-tools/* "$ANDROID_HOME/cmdline-tools/latest/"
            export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
            sudo apt install android-sdk-build-tools
            sudo apt install android-sdk-platform-tools
      - run:
          name: accept licenses
          command: |
            ls /usr/lib/android-sdk/tools/bin
            yes | /usr/lib/android-sdk/tools/bin/sdkmanager skdmanager --licenses
      - run:
          name: build android
          path: ./android
          command: ./gradlew assembleDebug
    environment:
      ANDROID_HOME: /usr/lib/android-sdk
