version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:19.0
    orbs:
      android: "2.1.2"
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@8.19"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - run:
          name: install ionic cli
          command: "sudo npm install -g @ionic/cli"
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: ionic build --prod
      - run:
          name: sync capacitor
          command: npx cap sync
      - run:
          name: build android
          command: ionic capacitor build android
