default_platform(:ios)

platform :ios do
  desc "Build ios"
  lane :build_ios do
    gym(scheme: "App")
  end
   desc "Upload to testfligjt"
    lane :upload_to_testflight do
      upload_to_testflight
    end
end
